import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { projects } from '@/data/projects';
import CompareSlider from '@/components/CompareSlider';

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);return {title:p?`${p.title} — AURELIS`: 'Project — AURELIS',description:p?.description};}
export default async function ProjectDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();return <main className="detail-page"><header className="detail-nav"><Link className="brand" href="/"><span>AURELIS</span><small>ARCHITECTURE + BUILD</small></Link><Link href="/#projects"><ArrowLeft size={14}/> ALL PROJECTS</Link><Link className="detail-cta" href="/#planner">START A PROJECT <ArrowUpRight size={14}/></Link></header><section className="detail-hero" style={{backgroundImage:`linear-gradient(0deg,rgba(9,9,8,.56),transparent 75%),url("${p.heroImage}")`}}><div className="detail-hero-inner"><span>PROJECT / {p.category.toUpperCase()} / {p.year}</span><h1>{p.title}<em>.</em></h1><p>{p.location} · {p.area}</p></div><span className="demo-image-label">DEMO PROJECT · PLACEHOLDER IMAGERY</span></section><section className="detail-meta">{[['LOCATION',p.location],['AREA',p.area],['YEAR',p.year],['TYPE',p.category],['STATUS',p.status]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</section><section className="detail-story"><div className="detail-sticky"><span>01 — THE WORK</span><h2>{p.title}<br/><em>in context.</em></h2><p>{p.description}</p><Link href="/#planner">DISCUSS A PROJECT <ArrowUpRight size={14}/></Link></div><div className="detail-chapters"><article><span>CONCEPT</span><p>{p.concept}</p></article><article><span>DESIGN CHALLENGE</span><p>{p.challenge}</p></article><article><span>MATERIAL PALETTE</span><ul>{p.materials.map(x=><li key={x}>{x}</li>)}</ul></article><article><span>SPATIAL STRATEGY</span><p>{p.strategy}</p></article></div></section><section className="detail-gallery"><div className="detail-gallery-head"><span>02 — GALLERY / CONCEPT IMAGERY</span><p>Illustrative images are placeholders for this demo and do not represent completed work.</p></div><div className="gallery-grid">{p.gallery.map((src,i)=><div key={src} className={`gallery-image gallery-${i+1}`} style={{backgroundImage:`url("${src}")`}}><span>0{i+1} / STUDY IMAGE</span></div>)}</div></section><section className="compare-section"><div><span>03 — DESIGN EVOLUTION</span><h2>Before.<br/>Design.<br/><em>Built.</em></h2><p>Drag to compare these stages. This interactive strip is a sample project presentation.</p></div><CompareSlider image={p.heroImage} secondary={p.gallery[0]}/></section><section className="detail-next"><span>HAVE A SITE IN MIND?</span><h2>Let’s begin<br/><em>with a conversation.</em></h2><Link className="button button-dark" href="/#planner">BUILD YOUR BRIEF <ArrowUpRight size={15}/></Link></section><footer className="footer"><Link href="/" className="footer-logo">AURELIS</Link><span>BENGALURU · INDIA</span><span>FICTIONAL STUDIO / DEMO EXPERIENCE</span><Link href="/#projects">ALL PROJECTS ↑</Link></footer></main>}
