'use client';
import { useRef, useState } from 'react';
import { useInView, motion } from 'framer-motion';
import { ArrowUpRight, MoveRight } from 'lucide-react';
import { projects } from '@/data/projects';

const cities=[{name:'Bengaluru',x:52,y:49},{name:'Mysuru',x:42,y:60},{name:'Hyderabad',x:65,y:34},{name:'Goa',x:26,y:34},{name:'Chennai',x:72,y:59}];
export function ProjectMap(){const [city,setCity]=useState('Bengaluru');const cityProject=projects.find(p=>p.location===city);return <section className="footprint section" id="footprint"><div className="business-head"><span className="micro-label">17 / OUR FOOTPRINT · SAMPLE</span><h2>Work begins<br/><em>with a place.</em></h2><p>Sample studio locations, marked on a quiet regional study. Select a city to see an imagined project.</p></div><div className="footprint-layout"><div className="footprint-map"><svg viewBox="0 0 100 100" role="img" aria-label="Schematic map of southern India"><path d="M18 16 36 10 48 18 57 14 72 22 75 31 85 38 77 48 81 59 71 67 67 82 58 91 51 78 42 74 40 64 32 59 31 49 24 42 21 31Z"/><path d="m32 22 11 12-7 13 12 10-6 14m18-49-4 15 10 9-7 13m-33-7 12 3 6 13"/></svg>{cities.map(c=><button key={c.name} className={`map-point ${city===c.name?'active':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}} onMouseEnter={()=>setCity(c.name)} onFocus={()=>setCity(c.name)} onClick={()=>setCity(c.name)} aria-label={`Show sample work in ${c.name}`}><i/>{c.name}</button>)}<span className="map-note">SOUTH INDIA / SCHEMATIC</span></div><motion.div className="city-project" key={city} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}}><div className="city-image" style={{backgroundImage:`url("${cityProject?.heroImage||projects[0].heroImage}")`}}><span>IMAGINED PROJECT / DEMO</span></div><small>SELECTED CITY / {city.toUpperCase()}</small><h3>{cityProject?.title||'New conversations'}</h3><p>{cityProject?cityProject.description:'A sample location for future studio work and site conversations.'}</p><a href={cityProject?`/projects/${cityProject.slug}`:'#planner'}>EXPLORE THE PROJECT <ArrowUpRight size={14}/></a></motion.div></div></section>}

export function Panorama(){const ref=useRef<HTMLElement>(null);const visible=useInView(ref,{once:true,margin:'100px'});const [dragging,setDragging]=useState(false);const [offset,setOffset]=useState(0);const [zoom,setZoom]=useState(1);const [hot,setHot]=useState(0);const start=useRef({x:0,offset:0});const details=['Living room / garden edge','Dining court / filtered light','Arrival / shaded threshold'];return <section className="panorama-section section" id="step-inside" ref={ref}><div className="business-head"><span className="micro-label">16 / SPATIAL WALKTHROUGH · DEMO IMAGERY</span><h2>Step<br/><em>inside.</em></h2><p>A pan-and-zoom sample for an imagined Courtyard House interior. Drag the view, adjust the lens and select a point of interest.</p></div><div className="panorama-stage" onPointerDown={e=>{setDragging(true);start.current={x:e.clientX,offset}}} onPointerMove={e=>{if(dragging)setOffset(Math.max(-18,Math.min(18,start.current.offset+(e.clientX-start.current.x)/16)))}} onPointerUp={()=>setDragging(false)} onPointerLeave={()=>setDragging(false)} onWheel={e=>setZoom(Math.max(1,Math.min(1.45,zoom-e.deltaY*.0005)))} style={{cursor:dragging?'grabbing':'grab'}}>{visible&&<div className="panorama-image" style={{backgroundImage:'url("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=85")',transform:`scale(${zoom}) translateX(${offset}%)`}}/>}<div className="panorama-scrim"/><span className="panorama-tag">SAMPLE PANORAMA / NOT A COMPLETED PROJECT</span>{details.map((x,i)=><button key={x} className={`panorama-hot h${i+1} ${hot===i?'active':''}`} onPointerDown={e=>e.stopPropagation()} onClick={()=>setHot(i)} aria-label={`Show panorama detail ${i+1}`}>0{i+1}</button>)}<div className="panorama-caption"><span>COURTYARD HOUSE / INTERIOR STUDY</span><b>{details[hot]}</b><span>DRAG TO PAN · SCROLL TO ZOOM</span></div><div className="panorama-zoom"><button onClick={()=>setZoom(Math.max(1,zoom-.1))} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(1.45,zoom+.1))} aria-label="Zoom in">+</button></div></div></section>}

export function ImageTrail(){const [trail,setTrail]=useState<{x:number;y:number;image:string;id:number}[]>([]);const last=useRef(0);const images=projects.slice(0,5).map(p=>p.heroImage);const add=(e:React.PointerEvent<HTMLDivElement>)=>{if(e.pointerType==='touch')return;const now=Date.now();if(now-last.current<120)return;last.current=now;const rect=e.currentTarget.getBoundingClientRect();const id=now;setTrail(t=>[...t,{x:e.clientX-rect.left,y:e.clientY-rect.top,image:images[Math.floor(Math.random()*images.length)],id}].slice(-4));window.setTimeout(()=>setTrail(t=>t.filter(item=>item.id!==id)),850)};return <section className="image-trail-section"><div className="image-trail-desktop" onPointerMove={add}><span className="micro-label">11 / A MOVING INDEX</span><h2>Spaces we’ve<br/><em>imagined.</em></h2><p>Move through the field to reveal sample project studies.</p>{trail.map((item,i)=><motion.div key={item.id} className="trail-image" initial={{opacity:0,scale:.72,rotate:(i%2?4:-4)}} animate={{opacity:1,scale:1,rotate:i%2?2:-2}} exit={{opacity:0,scale:.78}} transition={{duration:.45}} style={{left:item.x,top:item.y,backgroundImage:`url("${item.image}")`}}/>)}</div><div className="image-trail-mobile"><span className="micro-label">11 / PROJECT STUDIES · SWIPE</span><div>{projects.slice(0,4).map(p=><article key={p.slug} style={{backgroundImage:`linear-gradient(0deg,rgba(10,10,9,.55),transparent 55%),url("${p.heroImage}")`}}><b>{p.title}</b><small>DEMO IMAGE / {p.location.toUpperCase()}</small></article>)}</div></div></section>}
